/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IParticipantsInterface extends utils.Interface {
  functions: {
    "changeDoerSuccessRate(address,bool)": FunctionFragment;
    "doerIsValid(address)": FunctionFragment;
    "newDoer(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "changeDoerSuccessRate" | "doerIsValid" | "newDoer"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "changeDoerSuccessRate",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "doerIsValid",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "newDoer",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "changeDoerSuccessRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doerIsValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newDoer", data: BytesLike): Result;

  events: {};
}

export interface IParticipants extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IParticipantsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    changeDoerSuccessRate(
      _addr: PromiseOrValue<string>,
      success: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    doerIsValid(
      _doer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    newDoer(
      _doer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  changeDoerSuccessRate(
    _addr: PromiseOrValue<string>,
    success: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  doerIsValid(
    _doer: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  newDoer(
    _doer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    changeDoerSuccessRate(
      _addr: PromiseOrValue<string>,
      success: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    doerIsValid(
      _doer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    newDoer(
      _doer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    changeDoerSuccessRate(
      _addr: PromiseOrValue<string>,
      success: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    doerIsValid(
      _doer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    newDoer(
      _doer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    changeDoerSuccessRate(
      _addr: PromiseOrValue<string>,
      success: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    doerIsValid(
      _doer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    newDoer(
      _doer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
