/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ParticipantsInterface extends utils.Interface {
  functions: {
    "changeDoerSuccessRate(address,bool)": FunctionFragment;
    "doerIsValid(address)": FunctionFragment;
    "doers(uint256)": FunctionFragment;
    "getSuccessRate()": FunctionFragment;
    "newDoer(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "changeDoerSuccessRate"
      | "doerIsValid"
      | "doers"
      | "getSuccessRate"
      | "newDoer"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "changeDoerSuccessRate",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "doerIsValid",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "doers",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSuccessRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "newDoer",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "changeDoerSuccessRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doerIsValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "doers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSuccessRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newDoer", data: BytesLike): Result;

  events: {};
}

export interface Participants extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ParticipantsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    changeDoerSuccessRate(
      _addr: PromiseOrValue<string>,
      success: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    doerIsValid(
      _doer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    doers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, BigNumber] & {
        addr: string;
        level: BigNumber;
        successOrders: BigNumber;
        failedOrders: BigNumber;
        registerDate: BigNumber;
      }
    >;

    getSuccessRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    newDoer(
      _doer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  changeDoerSuccessRate(
    _addr: PromiseOrValue<string>,
    success: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  doerIsValid(
    _doer: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  doers(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber, BigNumber] & {
      addr: string;
      level: BigNumber;
      successOrders: BigNumber;
      failedOrders: BigNumber;
      registerDate: BigNumber;
    }
  >;

  getSuccessRate(overrides?: CallOverrides): Promise<BigNumber>;

  newDoer(
    _doer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    changeDoerSuccessRate(
      _addr: PromiseOrValue<string>,
      success: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    doerIsValid(
      _doer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    doers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, BigNumber] & {
        addr: string;
        level: BigNumber;
        successOrders: BigNumber;
        failedOrders: BigNumber;
        registerDate: BigNumber;
      }
    >;

    getSuccessRate(overrides?: CallOverrides): Promise<BigNumber>;

    newDoer(
      _doer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    changeDoerSuccessRate(
      _addr: PromiseOrValue<string>,
      success: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    doerIsValid(
      _doer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSuccessRate(overrides?: CallOverrides): Promise<BigNumber>;

    newDoer(
      _doer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    changeDoerSuccessRate(
      _addr: PromiseOrValue<string>,
      success: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    doerIsValid(
      _doer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    doers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSuccessRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    newDoer(
      _doer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
