/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICommission,
  ICommissionInterface,
} from "../../contracts/ICommission";

const _abi = [
  {
    inputs: [],
    name: "increasePriority",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICommission__factory {
  static readonly abi = _abi;
  static createInterface(): ICommissionInterface {
    return new utils.Interface(_abi) as ICommissionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICommission {
    return new Contract(address, _abi, signerOrProvider) as ICommission;
  }
}
