/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ISet, ISetInterface } from "../../contracts/ISet";

const _abi = [
  {
    inputs: [],
    name: "indices",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "insert",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "remove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISet__factory {
  static readonly abi = _abi;
  static createInterface(): ISetInterface {
    return new utils.Interface(_abi) as ISetInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ISet {
    return new Contract(address, _abi, signerOrProvider) as ISet;
  }
}
